---
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
minimumRequiredVersion: 0.8.0
directories:
- path: config/_deps
  contents:
  - path: cf-for-k8s
    git:
      url: git@github.com:cloudfoundry/cf-for-k8s
      ref: v0.5.0
    includePaths:
    - config/**/*
    - config-optional/add-metrics-server-components.yml
    - config-optional/patch-metrics-server.yml
    - config-optional/remove-resource-requirements.yml
    - hack/generate-values.sh
    - hack/run-smoke-tests.sh
    - tests/smoke/**/*
