#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cc-api-service-account
  namespace: #@ data.values.system_namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cc-api-service-account-superuser
subjects:
- kind: ServiceAccount
  name: cc-api-service-account
  namespace: #@ data.values.system_namespace
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cc-worker-service-account
  namespace: #@ data.values.system_namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cc-worker-service-account-superuser
subjects:
- kind: ServiceAccount
  name: cc-worker-service-account
  namespace: #@ data.values.system_namespace
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

#! kpack registry credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: cc-kpack-registry-auth-secret
  namespace: #@ data.values.staging_namespace
  annotations:
    build.pivotal.io/docker: #@ data.values.kpack.registry.hostname
type: kubernetes.io/basic-auth
stringData:
  username: #@ data.values.kpack.registry.username
  password: #@ data.values.kpack.registry.password
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cc-kpack-registry-service-account
  namespace: #@ data.values.staging_namespace
secrets:
  - name: cc-kpack-registry-auth-secret

