apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: routebulksyncs.apps.cloudfoundry.org
spec:
  group: apps.cloudfoundry.org
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: routebulksyncs
    singular: routebulksync
    kind: RouteBulkSync
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            selector:
              type: object
            template:
              type: object
