#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:overlay", "overlay")

---
apiVersion: v1
kind: Secret
metadata:
  name: inlets-token
  namespace: istio-system
type: Opaque
data:
  token: #@ base64.encode(data.values.inlets_token)

#@overlay/match by=overlay.subset({"kind":"DaemonSet","metadata":{"name":"istio-ingressgateway"}})
---
spec:
  template:
    spec:
      containers:
      #@overlay/match by="name", missing_ok=True
      - name: inlets-client
        image: inlets/inlets:2.7.0
        imagePullPolicy: Always
        command: ["inlets"]
        args:
        - client
        - --remote=$(INLETS_REMOTE)
        - --upstream=http://localhost:80
        - --token-from=/var/inlets/token
        env:
        - name: INLETS_REMOTE
          value: #@ data.values.inlets_remote
        volumeMounts:
        - name: inlets-token-volume
          mountPath: /var/inlets/
      volumes:
      #@overlay/match by="name", missing_ok=True
      - name: inlets-token-volume
        secret:
          secretName: inlets-token